import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Header from '../components/Header/Header';
import '../styles/globals.css';
import ThemeToggle from '../components/Dummy/ThemeToggle'; // Importe o ThemeToggle

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

import { Quicksand } from 'next/font/google';

const quicksand = Quicksand({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
	variable: '--font-quicksand',
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${quicksand.variable} antialiased`}
			>
				<ThemeToggle /> {/* Botão para alternar o tema */}
				<Header />
				{children}
			</body>
		</html>
	);
}
